improved import-db

diff --git a/pm-sync/import-db b/pm-sync/import-db
--- a/pm-sync/import-db
+++ b/pm-sync/import-db
@@ -1,4 +1,11 @@
 #!/bin/sh
+die() {
+	echo "$1" >&2
+	exit 1
+}
+
+[ -r "$HOME/.my.cnf" ] || die "ERROR: ~/.my.cnf not found"
+
 FSSERVER="-h 10.10.0.250"
 PROCESSMAKER=""
 
