WiP

diff --git a/itaca-import/1-llxgesc-import b/itaca-import/1-llxgesc-import
--- a/itaca-import/1-llxgesc-import
+++ b/itaca-import/1-llxgesc-import
@@ -1,8 +1,22 @@
 #!/bin/sh
+die() {
+        echo "$1" >&2
+        exit 1
+}
 
 # $1 => "original" llxgesc.xml (export from itaca to "aula LliureX")
 
+# basic tests
+[ "$1" ] || die "usage: $0 LLXGESC_FILE"
+
+[ $(id -u) -eq 0 ] || die "You must be root to run this script"
+
+# check configuration files
+[ -r /root/.my.cnf ] || die "Missing mysql configurarion in /root/.my.cnf"
+export HOME=/root
+
 LLXGESC="$1"
+[ -r "$LLXGESC" ] || die "ERROR: usage: $0 LLXGESC_FILE"
 
 # 1. create new file with line feeds
 LLXGESC_LINES="$(tempfile)"
@@ -12,3 +26,17 @@ sed -e "s%<\([^\/]\)%\n<\1%g" "$LLXGESC" > "$LLXGESC_LINES"
 # extract "assignatures" to a new xml
 ASSIGNATURES_XML="$(tempfile)"
 sed -e "1,/<assignatures>/d;s%\(<\/assignatures>\)%\n\1%" "$LLXGESC_LINES" | sed -e "/<\/assignatures>/,\$d" > "$ASSIGNATURES_XML"
+
+mysql --local-infile=1 -N -B -e "use itaca; truncate table assignatures; load xml local infile '$ASSIGNATURES_XML' into table assignatures character set utf8 rows identified by '<assignatura>';"
+
+PROFES_XML="$(tempfile)"
+
+sed -e "1,/<professors>/d;s%\(<\/professors>\)%\n\1%" "$LLXGESC_LINES" | sed -e "/<\/professors>/,\$d" > "$PROFES_XML"
+
+# extraer dnis a un fichero
+# iterar por dni, parseando su bloque:
+#sed -ne "/005135856W/,/<\/professor>/{/<grupoassignatura>/p}" profes.xml
+
+cp "$PROFES_XML" profes.xml
+
+rm -f "$LLXGESC_LINES" "$ASSIGNATURES_XML" "$PROFES_XML"
